### ISSUE TITLE
SSL for custom domains

### ISSUE THREAD

**Issue by danmcclain** [firesidelabs/fireside#35]
Was discussed in the fireside slack, but wanted to add here to track

Idea to minimize (read: eliminate) cost for SSL certificates: use https://letsencrypt.org

**Comment by dan** [comment]
Thanks. I have some experience with Let's Encrypt, and might consider it sometime down the road if/when we renew our SSL certs.

Unfortunately, because our distributed load balancers handle the SSL connections (instead of the individual servers), doing the kind of on-the-fly generation for us or customers isn't possible.
