### ISSUE TITLE
301 Redirects

### ISSUE THREAD

**Issue by AngeloCoppola-WA** [firesidelabs/fireside#61]
This is a feature request for 301 redirects either at the domain level. 

There are several use cases:

- Whenever renaming a page slug
- For easy "over the air" URLs that redirect to more complex URLs. For example "podcast-name.com/tshirts" might redirect to a Spreadshirt site or an Etsy store.
- If a user deletes a page, s/he might want that URL to point to the home page or another page instead. 
- Google SEO best practices call for the server to return a 410 for permanently deleted pages, 404 for temporarily unavailable pages, and 301 for moved pages. I've found it's easiest just to 301 deleted pages to the home page or some other logical page.

**Comment by jamesmontemagno** [comment]
We would love to have a way to specify 301 redirects since our current urls are complex from Simplecast:

http://www.mergeconflict.fm/episodes/58285-merge-conflict-29-what-developers-ought-to-try-in-2017

There is no way from what we can find to add the /episodes/ into the slug so we would need re-directs for them if possible

**Comment by jamesmontemagno** [comment]
I think we can close this puppy out! working great!
