### ISSUE TITLE
Support button blocks the bottom of the left nav in admin panel

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#81]
Sometimes the "Support" button at the bottom of the left nav in the admin panel blocks the "news" link.  This happens in particular when the main content portion of the page (the right side) is shorter than the nav menu, so it won't allow additional vertical scrolling.

So for example, on the "hosts" page, where I only have 3 items listed, the nav is by far the longest portion of the page, we run into this issue.  Obviously smaller-screened computers like my 13" laptop experience this more frequently because there is less screen real estate and I can't just drag the window down further.

I've attached a screenshot to help illustrate the issue:
<img width="301" alt="screen shot 2017-01-17 at 7 47 38 pm" src="https://cloud.githubusercontent.com/assets/2416372/22047854/052b5e4e-dcef-11e6-98b7-f75408ed1c9e.png">

**Comment by dan** [comment]
I've seen this too, and I wish there was something we could do about it.

Although Zendesk is pretty amazing, this is one area where they fall down a bit. We cannot make that link a sidebar item or topbar link without fully integrating Fireside into their API and writing our own version of their support-request widget.

Nor can we put the link on the RHS, because that blocks the SUBMIT buttons used across the website.

Sort of a catch-22.
