### ISSUE TITLE
Sponsor are show Blank White square when no promo code is entered

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#83]
I can only assume that this is where the promo code would go. Sometimes our sponsors don't have promo codes:
![image](https://cloud.githubusercontent.com/assets/1676321/22359590/6bab1500-e3fd-11e6-995d-fa2ed95d201f.png)

**Comment by dan** [comment]
Good catch.

**Comment by dan** [comment]
@bynines Any thoughts here?

**Comment by jamesmontemagno** [comment]
It only appears to happen on desktop. Looking at it on mobile does seem to work alright:
![image](https://cloud.githubusercontent.com/assets/1676321/23145330/5f74d760-f782-11e6-9967-4213c385ca2d.png)

**Comment by bynines** [comment]
Updated so that in the event that a code isn't specified, 'n/a' will be displayed instead.

![image](https://cloud.githubusercontent.com/assets/53810/23261178/c5b5e108-f99a-11e6-8ffb-6c376fec9920.png)

**Comment by dan** [comment]
I thought you'd do something fancy with CSS for this ... but DERPY DERP yes I can do this programatically.

So instead of "N/A" now we just don't output the block at all, and it seems to look just dandy.

![screen shot 2017-02-23 at 11 16 38 am](https://cloud.githubusercontent.com/assets/219/23270522/b17295be-f9b9-11e6-8e05-3aeb438e220e.png)
